### ISSUE TITLE
Hash mismatch

### ISSUE THREAD

**Issue by xijiang** [JuliaBinaryWrappers/MKL_jll.jl#1] opened 2020-01-16 13:47 UTC
Resolving package versions...
┌ Error: Hash Mismatch!
│   Expected sha256:   2b787be944cb795c0bacbbffb159831caa3e0fb4f336c6137df145afc76f0ae3
│   Calculated sha256: 9d3046219634c64095bde98fca95ff92b3bdabdfba0f3979efe025bb86e9c53d
└ @ Pkg.PlatformEngines /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.3/Pkg/src/PlatformEngines.jl:985
ERROR: Unable to automatically install 'MKL' from '/home/xijiang/.julia/packages/MKL_jll/9puEf/Artifacts.toml'

**Comment by giordano** [comment] 2020-01-16 13:50
Duplicate of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/618, will be fixed by https://github.com/JuliaRegistries/General/pull/8035

**Closed by giordano** 2020-01-16 13:50 UTC

**Comment by xijiang** [comment] 2020-01-16 14:11
add MKL_jl still not working
add MKL_jl#master will do the job

**Comment by giordano** [comment] 2020-01-16 14:12
Did you update the registry?  Did you free `MKL_jll`?

**Comment by xijiang** [comment] 2020-01-16 14:13
Many thanks, didn't know that command. Now it's OK
